version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "bin/**",
  "examples/**",
  "stubs/**",
  "assets/**"
]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "php"
enabled = true
